---
images_dir: /images/base

docker_user: kubespray+buildvmimages
docker_host: quay.io
registry: quay.io/kubespray

images:
  ubuntu-2004:
    filename: focal-server-cloudimg-amd64.img
    url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-disk-kvm.img
    checksum: sha256:8faf1f5a27c956ad0c49dac3114a355fbaf1b2d21709e10a18e67213fbb95b81
    converted: false
    tag: "latest"

  ubuntu-2204:
    filename: jammy-server-cloudimg-amd64.img
    url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img
    checksum: sha256:d3f3f446bf35b2e58b82c10c8fa65525264efe5b0e398238f00ab670f49528ab
    converted: false
    tag: "latest"

  ubuntu-2404:
    filename: noble-server-cloudimg-amd64.img
    url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    checksum: sha256:0cf56a2b23b430c350311dbcb9221b64823a5f7a401b5cf6ab4821f2ffdabe76
    converted: false
    tag: "latest"

  fedora-39:
    filename: Fedora-Cloud-Base-39-1.5.x86_64.qcow2
    url: https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2
    checksum: sha256:ab5be5058c5c839528a7d6373934e0ce5ad6c8f80bd71ed3390032027da52f37
    converted: true
    tag: "latest"

  fedora-40:
    filename: Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2
    url: https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2
    checksum: sha256:ac58f3c35b73272d5986fa6d3bc44fd246b45df4c334e99a07b3bbd00684adee
    converted: true
    tag: "latest"

  fedora-coreos:
    filename: fedora-coreos-32.20200601.3.0-openstack.x86_64.qcow2.xz
    url: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20200601.3.0/x86_64/fedora-coreos-32.20200601.3.0-openstack.x86_64.qcow2.xz
    checksum: sha256:fe78c348189d745eb5f6f80ff9eb2af67da8e84880d264f4301faaf7c2a72646
    converted: true
    tag: "latest"

  almalinux-9:
    filename: AlmaLinux-9-GenericCloud-9.5-20241120.x86_64.qcow2
    url: https://repo.almalinux.org/almalinux/9.5/cloud/x86_64/images/AlmaLinux-9-GenericCloud-9.5-20241120.x86_64.qcow2
    checksum: sha256:abddf01589d46c841f718cec239392924a03b34c4fe84929af5d543c50e37e37
    converted: true
    tag: "latest"

  rockylinux-9:
    filename: Rocky-9-GenericCloud-Base-9.5-20241118.0.x86_64.qcow2
    url: https://download.rockylinux.org/pub/rocky/9.5/images/x86_64/Rocky-9-GenericCloud-Base-9.5-20241118.0.x86_64.qcow2
    checksum: sha256:069493fdc807300a22176540e9171fcff2227a92b40a7985a0c1c9e21aeebf57
    converted: true
    tag: "latest"

  debian-11:
    filename: debian-11-generic-amd64-20210814-734.qcow2
    url: https://cdimage.debian.org/cdimage/cloud/bullseye/20210814-734/debian-11-generic-amd64-20210814-734.qcow2
    checksum: sha512:ed680265ce925e3e02336b052bb476883e2d3b023f7b7d39d064d58ba5f1856869f75dca637c27c0303b731d082ff23a7e45ea2e3f9bcb8f3c4ce0c24332885d
    converted: true
    tag: "latest"

  debian-12:
    filename: debian-12-generic-amd64-20230612-1409.qcow2
    url: https://cdimage.debian.org/cdimage/cloud/bookworm/20230612-1409/debian-12-generic-amd64-20230612-1409.qcow2
    checksum: sha512:61358292dbec302446a272d5011019091ca78e3fe8878b2d67d31b32e0661306c53a72f793f109394daf937a3db7b2db34422d504e07fdbb300a7bf87109fcf1
    converted: true
    tag: "latest"

  openeuler-2203:
    filename: openEuler-22.03-LTS-SP4-x86_64.qcow2.xz
    url: https://mirrors.ocf.berkeley.edu/openeuler/openEuler-22.03-LTS-SP4/virtual_machine_img/x86_64/openEuler-22.03-LTS-SP4-x86_64.qcow2.xz
    checksum: sha256:2dc9c9d73d172af0443d1a17786ee2e387006b9912fad24b5497ef103ecd7afb
    converted: true
    tag: "latest"

  openeuler-2403:
    filename: openEuler-24.03-LTS-x86_64.qcow2.xz
    url: https://mirrors.ocf.berkeley.edu/openeuler/openEuler-24.03-LTS/virtual_machine_img/x86_64/openEuler-24.03-LTS-x86_64.qcow2.xz
    checksum: sha256:c6af522d36d659b66da668cc4eb86b032a9cff05a95a0e37505a63e70ed585dc
    converted: true
    tag: "latest"

  flatcar-4081:
    filename: flatcar_production_kubevirt_image.qcow2
    url: https://stable.release.flatcar-linux.net/amd64-usr/4081.2.1/flatcar_production_kubevirt_image.qcow2
    checksum: sha512:6999ef068380c9842e4caf7afc2a1c66d4d03309f7bfa2f5f500757c36d1f935961f5662cc69376aa3d701e4c2d264f4356d4daadbb68e55becb710067e22c5d
    converted: true
    tag: latest
